### ISSUE TITLE
Optimizing the spatial data

### ISSUE THREAD

**Issue by cmahony** [joeyklee/bc-climate-explorer#7] opened 2017-02-16 19:01 UTC
Hi @joeyklee and @kevinkl , 
I'm starting on the task of getting a clean dataset together, and thinking about spatial data. One of my goals is to have a sliver-free shapefile. I haven't figured out a way to do sliver removal in R or ArcGIS (without ArcInfo license). I'm probably going to send my edited shapefile to Forsite (who offered in-kind GIS on this project) for generalization and sliver removal. 
In the beta version, we had a single shapefile. In this version, are we planning on doing anything fancy like managing zoom levels? let me know if there are things that i need to be considering as i move forward with  the spatial data processing

**Comment by joeyklee** [comment] 2017-03-05 12:42
Hi @kevinkl @cmahony,

Apologies for the slowness on my side. Its been really busy at work! 

Since maintaining the line quality was an important feature of the maps, I did a test converting the full res BGCv10Beta data and converted it to vector tiles using https://github.com/mapbox/tippecanoe

The resulting data file is pretty big ~518mb, but it works and is still performant since the vector tile stuff is blazingly fast. 

What I'm thinking now is maybe we can serve up the basedata using our own tileserver https://github.com/b-g/tilehut and then use Carto to serve up the data that we need. I'm not sure anymore if this make sense though and we might consider just migrating everything to our own server and database. 

here's a few images:
<img width="1487" alt="screen shot 2017-03-05 at 13 34 32" src="https://cloud.githubusercontent.com/assets/3622055/23587300/79675aea-01a9-11e7-89a0-725f5cfb5cde.png">
<img width="1487" alt="screen shot 2017-03-05 at 13 34 40" src="https://cloud.githubusercontent.com/assets/3622055/23587303/796d7bd2-01a9-11e7-8ba7-29e01d40d687.png">
<img width="1487" alt="screen shot 2017-03-05 at 13 34 49" src="https://cloud.githubusercontent.com/assets/3622055/23587302/796bd728-01a9-11e7-8d03-f4feca7b3c9a.png">
<img width="1487" alt="screen shot 2017-03-05 at 13 35 36" src="https://cloud.githubusercontent.com/assets/3622055/23587301/79691862-01a9-11e7-8423-d7bff7156b2a.png">

**Comment by kevinkl** [comment] 2017-03-06 10:51
Hey @joeyklee, no problem hope you still have fun at your work :)

I am not as familiar as you in the tileserver business, so I have some questions.

If we would do the first approach (with tilehut + Carto) can we just host the tilehut-server on github pages or do we need an extra server for that? If we don't need an extra server, we could try it with github pages + Carto and if this doesn't work we could still switch to our own server. What do you think?

When we would need to switch to our own server, which host would we choose? Do you know some free hoster or would we have to rent a server?

If you don't want to write all the answers down we can phone over Skype if you have time. Then I could also show you my code example that I completed today.

**Comment by cmahony** [comment] 2017-03-06 17:46
holy cow, that looks fantastic. this is really encouraging!

**Comment by joeyklee** [comment] 2017-03-06 20:44
Hi @kevinkl 
>If we would do the first approach (with tilehut + Carto) can we just host the tilehut-server on github pages or do we need an extra server for that? If we don't need an extra server, we could try it with github pages + Carto and if this doesn't work we could still switch to our own server. What do you think?

+ We would have to host the tileserver on OpenShift, but we could read in the data just as a URL. 
+ Yes, in this case the plan would be to send the vector tiles via a url included in our static html/javascript files hosted on github pages with Carto then serving up our data. 

> When we would need to switch to our own server, which host would we choose? Do you know some free hoster or would we have to rent a server?

+ I think the question is whether or not it makes sense to split up our workflow over these various platforms. On one hand, yes it is nice to have Carto taking care of a lot of our data handling needs, but this means we have data on carto, then tiles on openshift, then githubpages. It could in the end create more overhead and could also in the end be less reproducible. Yes, it is more or less free to go this route, but sometimes it pays to, well, pay ;)
+ One alternative is then to throw our data into a database like mongo and serve up our page via a node/express app and then send our tiles via openshift. But yeah not yet sure... maybe we need to do a prototype?

**Comment by kevinkl** [comment] 2017-03-06 21:58
Thanks for the answers, Joey!

I think a prototype is a great idea to check if this all going to work smoothly.

**Comment by joeyklee** [comment] 2018-05-14 13:25
Going to close this one now as we're serving up our tiles via Tilehut.js (https://github.com/b-g/tilehut) via DigitalOcean  at: tiles.jk-lee.com

**Closed as completed by joeyklee** 2018-05-14 13:25 UTC
